const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Behaviors.Tween,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Acts.RotateCounterclockwise,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.Else
	];
};
self.C3_JsPropNameTable = [
	{speedY: 0},
	{driftX: 0},
	{Planet: 0},
	{TouchLeft: 0},
	{TouchRight: 0},
	{lineScore: 0},
	{Rotate: 0},
	{Controller: 0},
	{BallLeft: 0},
	{BallRight: 0},
	{Keyboard: 0},
	{Touch: 0},
	{bgBalanceGame: 0},
	{textscore: 0},
	{Audio: 0},
	{Tween: 0},
	{PauseFrame: 0},
	{btnPaused: 0},
	{btnSfx: 0},
	{btnMusic: 0},
	{Settings: 0},
	{PauseBlank: 0},
	{texthighscore: 0},
	{LocalStorage: 0},
	{VarHighScore: 0},
	{varScore: 0},
	{isSfxOn: 0},
	{isMusicOn: 0}
];

self.InstanceType = {
	Planet: class extends self.ISpriteInstance {},
	TouchLeft: class extends self.ISpriteInstance {},
	TouchRight: class extends self.ISpriteInstance {},
	lineScore: class extends self.ISpriteInstance {},
	Controller: class extends self.ISpriteInstance {},
	BallLeft: class extends self.ISpriteInstance {},
	BallRight: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	bgBalanceGame: class extends self.ISpriteInstance {},
	textscore: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	PauseFrame: class extends self.ISpriteInstance {},
	btnPaused: class extends self.ISpriteInstance {},
	btnSfx: class extends self.ISpriteInstance {},
	btnMusic: class extends self.ISpriteInstance {},
	Settings: class extends self.ISpriteInstance {},
	PauseBlank: class extends self.ISpriteInstance {},
	texthighscore: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {}
}